### ISSUE TITLE
compile error  inlining failed in call to always_inline ‘_mm_alignr_epi8’ on unbantu20.04 gcc9

### ISSUE THREAD

**Issue by imayuxiang** [relic-toolkit/relic#177] opened 2021-01-23 06:20 UTC
r/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:139:5: note: called from here
  139 |  m1=_mm_alignr_epi8(m1,m0,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:160:3: note: in expansion of macro ‘LSHIFT8’
  160 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:138:5: note: called from here
  138 |  m2=_mm_alignr_epi8(m2,m1,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:160:3: note: in expansion of macro ‘LSHIFT8’
  160 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:137:5: note: called from here
  137 |  m3=_mm_alignr_epi8(m3,m2,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:160:3: note: in expansion of macro ‘LSHIFT8’
  160 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:139:5: note: called from here
  139 |  m1=_mm_alignr_epi8(m1,m0,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:160:3: note: in expansion of macro ‘LSHIFT8’
  160 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:138:5: note: called from here
  138 |  m2=_mm_alignr_epi8(m2,m1,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:160:3: note: in expansion of macro ‘LSHIFT8’
  160 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:137:5: note: called from here
  137 |  m3=_mm_alignr_epi8(m3,m2,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:160:3: note: in expansion of macro ‘LSHIFT8’
  160 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:139:5: note: called from here
  139 |  m1=_mm_alignr_epi8(m1,m0,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:170:3: note: in expansion of macro ‘LSHIFT8’
  170 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:138:5: note: called from here
  138 |  m2=_mm_alignr_epi8(m2,m1,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:170:3: note: in expansion of macro ‘LSHIFT8’
  170 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:137:5: note: called from here
  137 |  m3=_mm_alignr_epi8(m3,m2,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:170:3: note: in expansion of macro ‘LSHIFT8’
  170 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:139:5: note: called from here
  139 |  m1=_mm_alignr_epi8(m1,m0,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:170:3: note: in expansion of macro ‘LSHIFT8’
  170 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:138:5: note: called from here
  138 |  m2=_mm_alignr_epi8(m2,m1,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:170:3: note: in expansion of macro ‘LSHIFT8’
  170 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:33:
/usr/lib/gcc/x86_64-linux-gnu/9/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
  185 | _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
      | ^~~~~~~~~~~~~~~
In file included from /builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low.c:118:
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:137:5: note: called from here
  137 |  m3=_mm_alignr_epi8(m3,m2,15);\
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~
/builds/algorithm_team/pyaby/third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/low/curve2251-sse/relic_fb_mul_low_ld.c:170:3: note: in expansion of macro ‘LSHIFT8’
  170 |   LSHIFT8(m3, m2, m1, m0);
      |   ^~~~~~~
make[2]: *** [third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/CMakeFiles/relic_s.dir/build.make:1077: third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/CMakeFiles/relic_s.dir/low/curve2251-sse/relic_fb_mul_low.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:319: third_party/ABY/extern/ENCRYPTO_utils/extern/relic/src/CMakeFiles/relic_s.dir/all] Error 2

**Comment by dfaranha** [comment] 2021-01-25 16:21
It looks like a toolchain problem, so I need more information to reproduce this issue.

What are you trying to build and how?

**Comment by imayuxiang** [comment] 2021-01-26 07:20
I want to build ABY, which relyed on ENCRYPTO_utils, and ENCRYPTO_utils used relic. I have complied it with sse3 flag, but it does not work

**Comment by dfaranha** [comment] 2021-01-26 07:23
Can you give a sequence of steps to reproduce?
Can you try building with -march=native in your machine?

**Comment by dfaranha** [comment] 2021-03-24 10:33
It's been a month and I still cannot reproduce, hence closed.

**Comment by Oleksandr-Tkachenko** [comment] 2021-06-29 12:46
I'm experiencing the same problem, which is also related to https://github.com/relic-toolkit/relic/issues/178. Namely, `ENCRYPTO_utils` [used](https://github.com/encryptogroup/ENCRYPTO_utils/blob/96e724c822ffc1e8aa397b9142874620d6d3243e/CMakeLists.txt#L46) `COMP` to set the appropriate compiler flags, but now `COMP` is not used anymore and `CFLAGS` is ignored if it doesn't originate from the terminal flags. Would it be possible to append custom compiler flags via cmake directly, in addition to the ones from the terminal?

**Comment by dfaranha** [comment] 2021-06-29 12:55
I thought the issue with CFLAGS was fixed. Perhaps I can reproduce if I follow encryptogroup/ENCRYPTO_utils#29

**Comment by dfaranha** [comment] 2021-06-29 13:14
Renaming `COMP` to `CFLAGS` in the `CMakeLists.txt` within `ENCRYPTO_utils` solved it for me. Can you please try?

**Comment by Oleksandr-Tkachenko** [comment] 2021-06-30 06:20
It indeed started working after removing the cmake cache, thanks a lot for your help @dfaranha!

On the other hand, IMO it might still be a good idea to use relic-specific flags for that, e.g., `RELIC_COMPILE_OPTIONS`, and put them into
```
target_compile_options(${RELIC} ${RELIC_COMPILE_OPTIONS})
```
to avoid setting the options globally. What do you think?

**Comment by dfaranha** [comment] 2021-06-30 17:39
Quite possibly, I need to look at best practices in other CMake projects. There are a lot of variables to prefix in the configuration, and we will eventually get there after prefixing all internal symbols in RELIC.

Closing for now, thanks for the check!

**Closed by dfaranha** 2021-06-30 17:39 UTC
