### ISSUE TITLE
 ‘ctx_t’ {aka ‘struct _ctx_t’} has no member named ‘total’

### ISSUE THREAD

**Issue by xiahaijiao** [relic-toolkit/relic#168] opened 2021-01-12 03:16 UTC
relic_bench.c:166:12: error: ‘ctx_t’ {aka ‘struct _ctx_t’} has no member named ‘total’
  core_get()->total = 0;

**Comment by dfaranha** [comment] 2021-01-12 09:34
I cannot reproduce. What is your config?

**Comment by dfaranha** [comment] 2021-02-07 01:10
Closing due to difficulty in reproducing.

**Closed by dfaranha** 2021-02-07 01:10 UTC
